services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: "postgres@localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    # эта папка используется для инициализации. В ней исполняются все .sql и .sh файлы
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    restart: always
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    restart: always