create table if not exists pets (
                                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     name varchar UNIQUE NOT NULL,
                                     age int NOT NULL,
                                     owner_id int NOT NULL
);

create table if not exists owner (
                                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                        name varchar UNIQUE NOT NULL
);